### ISSUE TITLE
STM32 based LwPKT Example

### ISSUE THREAD

**Issue by suyog44** [MaJerle/lwpkt#3]
Hi Majrele,

I am planning to construct Multi Device Communication over UART (RS485) protocol. I found LwPKT interesting project to use it. 
But i am unable to figure out the usage with STM32 UART Interrupt based function. Could you able to give some hints regarding it. 

/* Start DMA */
    if(HAL_UART_Receive_DMA(&huart2, (uint8_t*)pkt_tx_rb_data, 64) != HAL_OK)
    {        
        Error_Handler();
    }

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
     res = lwpkt_write(&pkt,
		
		#if LWPKT_CFG_USE_ADDR
							0x11,                       /* End address to whom to send */
		#endif /* LWPKT_CFG_USE_ADDR */

		#if LWPKT_CFG_USE_CMD
							0x85,                       /* Command type */
		#endif /* LWPKT_CFG_USE_CMD */
							data, strlen(data));        /* Length of data and actual data */
}

**Comment by MaJerle** [comment]
Lwpkt uses lwrb libraryand therefore received bytes over uart must be written to rx buffer of lwpkt ibstabce through lwrb_write function
