### ISSUE TITLE
top-level CMakeLists.txt, project not buildable

### ISSUE THREAD

**Issue by ic17b033** [MaJerle/lwpkt#4]
The  cmake variable "PROJECT_IS_TOP_LEVEL" is used in top-level CMakeLists.txt , which is available since cmake version 3.21 according to cmake.org, although the version 3.0.0 is required by the Project.

**Comment by MaJerle** [comment]
You are absolutely right. Will get fixed very soon.
Thanks for this report.

**Comment by MaJerle** [comment]
Fixed: https://github.com/MaJerle/lwpkt/commit/9ec9c65f75c2ca9cfa5fdaed6a77c2696944c651
