### ISSUE TITLE
版本V1.2.0，LWPKT_CFG_USE_CRC = 0，编译报错

### ISSUE THREAD

**Issue by ShaoMingya** [MaJerle/lwpkt#6]
版本V1.2.0中，lwpkt.c第56行：
#define ADD_IN_TO_CRC(val)
编译报错：
lwpkt.c(181): error:  #55-D: too many arguments in invocation of macro "ADD_IN_TO_CRC"

**Comment by MaJerle** [comment]
Fixed on develop branch
