### ISSUE TITLE
Possible missing preprocessor #if macro

### ISSUE THREAD

**Issue by tommasoclini** [MaJerle/lwpkt#9]
I'm compiling the library, with cmd disabled, so in lwpkt_opts: #define LWPKT_CFG_USE_CMD 0.
When compiling, I get an error on line 611 of lwpkt.c, there is an "undeclared, first use in this functions" kind of error, it is referring to cmd, used inside the second if of the two about command, is a #if LWPKT_CFG_USE_CMD necessary for those two ifs?

**Comment by MaJerle** [comment]
https://github.com/MaJerle/lwpkt/commit/e0747b3eba57a20eafb1dfbfe209118f54aa3a70
